name: ci-pipeline

on:
 push:
  branches:
    - feature*

  paths-ignore:
    - '**/*.md'
    - '**/*.gitignore'

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    env:
      solutionPath: src/Poke.API.Facade.sln
    
    steps:

      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup dot net
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 3.1.x
      
      - name: Build code
        run: dotnet build ${{env.solutionPath}}
      
      - name: Make Directory for test results
        run: mkdir -p testresults

      
      - name: Run Xunit Tests
        run: dotnet test ${{env.solutionPath}} --logger html --results-directory testresults
      
      
      - name: Upload Test results
        uses: actions/upload-artifact@v2
        with:
          name : TestRunReports
          path: TestResults
  
  create-pull-request:
    needs: build-and-test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Create a Pull request
        uses: repo-sync/pull-request@v2
        with: 
          destination_branch: "main"                      
          pr_title: "Pulling ${{ github.ref }} into master" 
          pr_body: ":robot: *Web API bot raised the PR*"
          pr_reviewer: "fullstackmaddy"                                          
          pr_label: "autopr"                              
          pr_draft: false                                  
          pr_allow_empty: false                            
          github_token: ${{ secrets.GITHUB_TOKEN }}

